<?php

/**
 * @file
 * Module file for Islandora Change Cmodel.
 */

/**
 * Implements hook_menu().
 */
function islandora_change_cmodel_menu() {
  $items = array();
  $items['admin/islandora/tools/change_cmodel'] = array(
    'title' => 'Change Content Model',
    'description' => 'Configure Islandora Change Content Model.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_change_cmodel_admin_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['islandora/object/%islandora_object/change_cmodel'] = array(
    'title' => 'Change content model',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_change_cmodel_change_model_form'),
    'file' => 'includes/change_model.form.inc',
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_change_cmodel_access_callback',
    'access arguments' => array(
      array(
        ISLANDORA_MANAGE_PROPERTIES,
        ISLANDORA_ADD_DS,
        ISLANDORA_REGENERATE_DERIVATIVES,
        ISLANDORA_REPLACE_DATASTREAM_CONTENT,
        'change Islandora object cmodels',
      ), 2),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_change_cmodel_permission() {
  return array(
    'change Islandora object cmodels' => array(
      'title' => t('Change Islandora Content Models'),
      'description' => t('Change Islandora object content model'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function islandora_change_cmodel_form_islandora_object_properties_form_alter(&$form, &$form_state) {
  module_load_include('inc', 'islandora_change_cmodel', 'includes/utilities');
  $object = islandora_object_load($form_state['object']);
  $allowed_cmodels_on_object = islandora_change_cmodel_check_for_cmodels($object);
  if (count($allowed_cmodels_on_object) > 0 && islandora_user_access($object, array('change Islandora object cmodels'))) {
    $form['change_cmodel'] = array(
      '#type' => 'submit',
      '#value' => t("Change content model"),
      '#submit' => array('islandora_change_cmodel_show_confirm_form'),
    );
  }
}

/**
 * Redirect user to content model change form.
 */
function islandora_change_cmodel_show_confirm_form($form, $form_state) {
  drupal_goto("islandora/object/{$form_state['object']}/change_cmodel");
}

/**
 * Checks whether the user can access an object's "Change content model" button.
 *
 * @param array $perms
 *   Array of user permission to test for.
 * @param AbstractObject $object
 *   The object to test, if NULL given the object doesn't exist or is
 *   inaccessible.
 *
 * @return bool
 *   TRUE if the user is allowed to access this object, FALSE otherwise.
 */
function islandora_change_cmodel_access_callback($perms, $object = NULL) {
  module_load_include('inc', 'islandora_change_cmodel', 'includes/utilities');
  $allowed_cmodels_on_object = islandora_change_cmodel_check_for_cmodels($object);

  if (islandora_user_access($object, array('change Islandora object cmodels'))
    && islandora_object_manage_access_callback($perms, $object)
    && count($allowed_cmodels_on_object) > 0) {
    return TRUE;
  }
}
