<?php

/**
 * @file
 * Module file for Islandora Change Cmodel.
 */

/**
 * Implements hook_menu().
 */
function islandora_change_cmodel_menu() {
  $items = array();
  $items['admin/islandora/tools/change_cmodel'] = array(
    'title' => 'Change Content Model',
    'description' => 'Configure Islandora Change Content Model.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_change_cmodel_admin_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['islandora/object/%islandora_object/change_cmodel'] = array(
    'title' => 'Change content model',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_change_cmodel_confirm_form'),
    'file' => 'includes/confirm.form.inc',
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_change_cmodel_access_callback',
    'access arguments' => array(
      array(
        ISLANDORA_MANAGE_PROPERTIES,
        ISLANDORA_METADATA_EDIT,
        ISLANDORA_ADD_DS,
        ISLANDORA_PURGE,
        ISLANDORA_INGEST,
      ), 2),
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function islandora_change_cmodel_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'islandora_object_properties_form') {
    $form['change_cmodel'] = array(
      '#type' => 'submit',
      '#value' => t("Change content model"),
      '#submit' => array('islandora_change_cmodel_show_confirm_form'),
    );
  }
}

function islandora_change_cmodel_show_confirm_form($form, $form_state) {
  drupal_goto("islandora/object/{$form_state['object']}/change_cmodel");
}

/**
 * Checks whether the user can access the given object's 'Clone' tab.
 *
 * @param array $perms
 *   Array of user permission to test for.
 * @param AbstractObject $object
 *   The object to test, if NULL given the object doesn't exist or is
 *   inaccessible.
 *
 * @return bool
 *   TRUE if the user is allowed to access this object, FALSE otherwise.
 */
function islandora_change_cmodel_access_callback($perms, $object = NULL) {
  module_load_include('inc', 'islandora_change_cmodel', 'includes/utilities');
  $object_models = $object->models;
  $allowed_models = variable_get('islandora_change_cmodel_allowed_cmodels', array());
  $allowed_models_filtered = array();
  foreach ($allowed_models as $key => $value) {
    if ($value != '0') {
      $allowed_models_filtered[] = $value;
    }
  }
  $intersection = array_intersect($object_models, $allowed_models_filtered);

  if (islandora_object_manage_access_callback($perms, $object) && count($intersection) > 0) {
    return TRUE;
  }
}
